### ISSUE TITLE
The problem with launching the game.

### ISSUE THREAD

**Issue by wojtekschiller3** [suomipelit/skijump3-sdl#16] opened 2020-12-15 17:57 UTC
Hello!

I have a problem with the game that has appeared since the first version that came out, SP1. The problem is that when I want to start the game via SJ3.exe, a white window appears for a split second and the game switches off after a while. 

Out of curiosity I tried to fire the game via the command line. Here is what the error message showed up;
[https://i.imgur.com/zOtuYkU.png](url)

 Is it possible to find out what may cause this error? I will point out that it is trying to start the game on Windows 10.

Greetings!

**Comment by wojtekschiller3** [comment] 2020-12-15 19:45
EDIT:

It turned out that the game only started when I chose the integrated graphics card. I am still waiting for such a bug to be fixed. Greetings!

**Comment by veikkos** [comment] 2020-12-15 20:11
Hey, thanks for reporting the issue!

Could you try to reproduce it with attached debug version? Extract it into fresh SJ3 directory and run from command line. It should print more information than the release version. Thanks!

[SJ3-debug.zip](https://github.com/suomipelit/skijump3-sdl/files/5698330/SJ3-debug.zip)

**Comment by wojtekschiller3** [comment] 2020-12-16 15:29
https://i.imgur.com/orQqy0T.png

Hello.
After activating SJ3-debug.exe, more information came out of the command line. I hope this will help solve the problem.

Cheers!

**Comment by veikkos** [comment] 2020-12-16 16:12
Thanks! It's indeed helpful and shows that the problem happens within renderer creation.

```
  renderer := SDL_CreateRenderer(window, -1, 0); 
```

I checked the parameters we use in Window and Renderer creation and those should be valid. I couldn't find search engine hits for this kind of exception related to that API.

Because you are the only one out of hundreds of users who have reported this and with dedicated GPU only, I'm inclined to say that the issue is either in SDL library, operating system or most likely in GPU drivers.

Which dedicated GPU you have? Is it in laptop? Can you try to update your GPU drivers?

**Comment by veikkos** [comment] 2020-12-16 16:17
One thing we could try. This version enforces software rendering instead of defaulting to hardware acceleration. Could you try if this one works with your problematic GPU? Thanks!

[SJ3-sw-renderer.zip](https://github.com/suomipelit/skijump3-sdl/files/5703971/SJ3-sw-renderer.zip)

**Comment by wojtekschiller3** [comment] 2020-12-16 16:31
My dedicated graphics card is the NVIDIA GeForce GTX 1650, and yes, I have a laptop. As for the graphics drivers, I have everything updated.

However, after running SJ3-sw-renderer.exe file on NVIDIA card, the game started normally, without any errors.

Thank you very much!

**Comment by veikkos** [comment] 2020-12-16 18:33
Thanks for testing. What the test actually means is that the problem is indeed only with that particular nVIDIA setup/drivers. The change forced software rendering which means that all the work is done by the CPU. This test was unfortunately only a workaround and cannot be mainlined since it removes any GPU hardware acceleration from everyone.

It all means that there does not seem to be a way to fix the issue in code. Have you played other SDL2 games like [what we have ported](https://suomipelit.github.io/) or maybe [C-Dogs](https://github.com/cxong/cdogs-sdl/releases/tag/0.10.1)? It would be interesting to know if some or all of them work.

**Comment by wojtekschiller3** [comment] 2020-12-16 18:51
I have not yet played the other games, I would have to look at them in the near future and see if there is a similar error. So, as I understand it, my only option is to play the integrated graphics card. Well, there is always a solution :D Thanks a lot for your help! :)

**Comment by veikkos** [comment] 2020-12-19 14:06
I'm adding [a command line parameter](https://github.com/suomipelit/skijump3-sdl/compare/sw-renderer-option) to prioritize SW rendering. It's at least a valid workaround.

I was looking online and there were some Pascal/SDL issues with similarities. But nothing really promising. I tried to repro on one nVidia laptop but that was ok.

**Comment by veikkos** [comment] 2020-12-20 15:57
[SJ313-SP4](https://github.com/suomipelit/skijump3-sdl/releases/tag/sj313-sp4) released with support for enforced SW rendering via [command line parameters](https://github.com/suomipelit/skijump3-sdl#command-line-parameters).

Thanks again for reporting and have a nice flight to Christmas! Stay safe.

**Closed by veikkos** 2020-12-20 15:57 UTC
Labels: bug
